[package]
edition = "2024"
# rust-version = "1.75"
name = "flatland"
version = "0.52.0"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Flat panel UI client for Stardust XR like SimulaVR or xrdesktop"
license = "MIT"
repository = "https://github.com/StardustXR/flatland/"
homepage = "https://stardustxr.org"

[patch.crates-io]
gluon-ipc-codegen.git = "https://github.com/StardustXR/gluon-ipc"
gluon-ipc.git = "https://github.com/StardustXR/gluon-ipc"

[features]
tracy = ["dep:tracing-tracy", "dep:tracy-client"]

[dependencies]
glam = { version = "0.33.7", features = ["mint"] }
tokio = { version = "1.38.0", features = ["full"] }
input-event-codes = "6.2.0"
rustc-hash = "1.1.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
colorgrad = "0.6.2"
derive_setters = "0.1.6"
derive-where = "1.2.7"
serde = { version = "1.0.216", features = ["derive"] }
tracing-tracy = { version = "0.11.4", optional = true }
tracy-client = { version = "0.18.0", optional = true }
clap = { version = "4.6.6", features = ["derive"] }

[profile.dev]
panic = "abort"

[dependencies.gluon-ipc]
version = "0.1.0"
# git = "https://github.com/StardustXR/gluon-ipc"

[dependencies.stardust-xr-fusion]
version = "0.52.0"
# git = "https://github.com/StardustXR/core"

[dependencies.stardust-xr-molecules]
version = "0.52.0"
# git = "https://github.com/StardustXR/molecules"

[dependencies.stardust-xr-asteroids]
version = "0.52.0"
# git = "https://github.com/StardustXR/asteroids"

[dependencies.stardust-xr-panels]
# version = "0.52.0"
git = "https://github.com/StardustXR/panel-item"

[dependencies.stardust-xr-panels-asteroids]
# version = "0.52.0"
git = "https://github.com/StardustXR/panel-item"
